<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXkiikox\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXkiikox/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXkiikox.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXkiikox\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXkiikox\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xkiikox',
    'container.build_id' => 'dc9c5d6c',
    'container.build_time' => 1619558315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXkiikox');
